server:
  listen: 0.0.0.0
  port: 8080
contact:
  mail: sec@uauth.io
  matrix: "@i401:xn--vl1a.moe"
  threema: WDVTAHX7
content:
  secret: 
  wiki:
    repository: https://github.com/b401/wiki.git
    path: /tmp/wiki
  blog:
    repository: https://github.com/b401/blog.git
    path: /tmp/blog
