server:
  listen: 0.0.0.0
  port: 8080
  host: https://uauth.io
index:
  slogan: 仕方がない
  title: i401
  github: b401
  skills:
    - Go, Rust, C, Powershell and other stuff
    - Useless (and useful) Microsoft knowledge
    - GNU/Linux connoisseur
    - Red/Blue and purple team
contact:
  mail: sec@uauth.io
  matrix: "@i400:xn--vl1a.moe"
  threema: WDVTAHX7
content:
  secret: super-secret-webhook-key 
  wiki:
    repository: https://github.com/b401/wiki.git
    path: /tmp/wiki
  blog:
    repository: https://github.com/b401/blog.git
    path: /tmp/blog
